graph LR
    bus([Internal service bus])
    queue[(Processor queue)]
    adaptor[Adaptor]
    task[Task]
    ext(External system)
    bus <--> adaptor
    task <--> ext
    subgraph proc[ProSA Processor]
    queue <--> task
    adaptor <--> task
    end
