---
name: ProSA-Book

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
        run: |
          cargo install mdbook-mermaid
          prosa_book/init.sh
          mdbook build prosa_book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prosa_book/book
